### ISSUE TITLE
How to run keyboard_teleop.launch properly

### ISSUE THREAD

**Issue by iqedgarmg** [pal-robotics/reemc_tutorials#1]
Hi everyone! 

I am trying to run the reemc simulation using the basic tutorials, I see that there exist a node called "keyboard_teleop" inside the basic_tutorials package. Nevertheless, I can't find a documentation of how to run it properly.

First I tried to run the basic gazebo simulation: 

roslaunch reemc_gazebo reemc_empty_world.launch

Then, run the joint controllers: 

roslaunch reemc_controller_configuration joint_trajectory_controllers.launch  

And finally, the keyboard node: 

roslaunch reemc_basic_tutorials keyboard_teleop.launch 

Nevertheless, the robot is not moving. By verifying the topic "joy (sensor_msgs/Joy)" I see that it is published all the time by the first node. 

How can I use the node to make the robot walking (on simulation) using the keyboard?. 

Thanks in advance for your response!

**Comment by saikishor** [comment]
Hello @iqedgarmg,

Thanks for showing interest in our REEM-C simulation. For the robot to walk in simulation, you would need `walking_controller`. Unfortunately, this walking controller is our proprietary software and it is not open to public.

You could try other interesting REEM-C tutorials at [http://wiki.ros.org/Robots/REEM-C/Tutorials](http://wiki.ros.org/Robots/REEM-C/Tutorials)

Thank you,

**Comment by iqedgarmg** [comment]
Hi @saikishor, thanks for your quick response. 

My university bought the reemc robot some years ago, and we have the physic robot working. Nevertheless, I want to simulate some routines prior executing it on the real robot. 

If I provide you the purchase information (via email) can you provide me that node? 

Thanks in advance for your response. 

Greetings!

**Comment by saikishor** [comment]
@iqedgarmg 

Thanks for getting back to us. In this case, could you open a support ticket at [support.pal-robotics.com](http://support.pal-robotics.com)?. We could help you from there.

Moreover, you can find the node installed in the provided development ISO to test it in the simulation.

**Comment by iqedgarmg** [comment]
@saikishor  

Excellent thanks!. 

I will open the support ticket. 

Greetings!

**Comment by iqedgarmg** [comment]
Hi @saikishor  

Can I ask you a last question prior open the support ticket?

In the reemc_tutorials node, I find a "simple_effort_control" launch file.  When I run the standard simulation: 

roslaunch reemc_gazebo reemc_empty_world.launch 

I notice that a joint controller is enabled by default (due to the robot remains stand). I want to allow a basic simulation where I can define forces to apply to every joint in order to design my own controllers. 

Is there a launch file or node in the repository that enables this type of simulation?. 

* Publishing basic joint's information (joint_states, /floating_base_pose_simulated, /right_ankle_ft, /right_ankle_ft topics) 
* Robot model free of any controller applied, or enabled to read a topic with desired efforts to apply to every joint. 

Thanks in advance for your response!
