### ISSUE TITLE
Unable to connect a client using MoveJointGroup class

### ISSUE THREAD

**Issue by iqedgarmg** [pal-robotics/reemc_tutorials#2]
Hello everyone!. 

I am trying to use the MoveJointGroup class to move several robot joints at the same time. I wrote a simple node inside the play_motion node to develop this task for two joints on the left_arm: 

```
//Import basic libraries
#include <ros/ros.h>
#include <stdio.h>
#include <iostream>

//Play_motion libraries
#include "play_motion/move_joint_group.h"
#include <play_motion_msgs/PlayMotionResult.h>

//ROS messages
#include <trajectory_msgs/JointTrajectoryPoint.h>
#include <ros/duration.h>

int main(int argc, char** argv)
{
    //Init ros node
    ros::init(argc, argv, "joint_controller");
    ros::NodeHandle n("~");

    //Init controller information
    const std::string cont_name = "left_arm_controller";

    //Set joint names
    const std::vector<std::string> joint_names = std::vector<std::string>{std::string{"arm_left_1_joint"}, std::string{"arm_left_2_joint"}};

    //Init client service
    play_motion::MoveJointGroup* control_service = new play_motion::MoveJointGroup(cont_name, joint_names);

    //Build example trajectory
    std::vector<trajectory_msgs::JointTrajectoryPoint> traj;
    trajectory_msgs::JointTrajectoryPoint msg; 
    msg.positions = {3.14, 0.0};
    msg.time_from_start = ros::Duration(0.5);
    traj.push_back(msg);

    //Verify client connection
    std::cout << "global state: " << control_service->getState().getText() << std::endl;
    for(int j = 0; j < joint_names.size(); j++)
    {
        std::cout << joint_names[j] << ": " << control_service->isControllingJoint(joint_names[j]) << std::endl;
    }

    //Send goal
    control_service->sendGoal(traj);
}
```

Both connection verifications return false, and the robot is not responding. Also, no message is displayed in the main gazebo node (as is displayed using the play_motion python node to move single joints).

Am I missing some part or instruction in the code? 

Thanks in advance for your response!

**Comment by saikishor** [comment]
Hello @iqedgarmg 

Thanks for writing to us. Regarding your query, it seems that the joint_trajectory_controllers are not started. By default, the robot is launched with no controllers. Run the following controller, to launch the controllers:
`roslaunch reemc_controller_configuration joint_trajectory_controllers.launch`

You can also check the currently loaded controllers, using the following command:
`rosservice call /controller_manager/list_controllers`

Thank you,

**Comment by iqedgarmg** [comment]
Hi @saikishor, thanks again for your quick response! 

Yes, I run the main gazebo node: 

`roslaunch reemc_gazebo reemc_empty_world.launch`
 
and then the controller node: 

`roslaunch reemc_controller_configuration joint_trajectory_controllers.launch`

which prints the output: 

`
[INFO] [1618820055.444422, 7.586000]: Started controllers: left_leg_controller, right_leg_controller, torso_controller, head_controller, left_arm_controller, right_arm_controller, left_hand_controller, right_hand_controller`

finally my own node (the node that I wrote in the previous comment). 

`rosrun play_motion position_controller `

The output of your last command is the following (the case of left_arm_controller): 

```
 - 
    name: "left_arm_controller"
    state: "running"
    type: "position_controllers/JointTrajectoryController"
    claimed_resources: 
      - 
        hardware_interface: "hardware_interface::PositionJointInterface"
        resources: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint,
  arm_left_6_joint, arm_left_7_joint]
```

If I for example, run the play_motion tutorial node instead my node: 

`rosrun play_motion move_joint arm_left_1_joint 1.5 0.5` 

Everything works fine. So I am not sure if I missing some part or instruction in my previous code.

**Comment by saikishor** [comment]
@iqedgarmg The current joint trajectory controllers configuration doesn't allow to command partial joints. You would need to publish the state of all the joints corresponding to the controller. I believe `move_joint` command internally fills up the current joint configuration for the rest of the joints. You can verify it by subscribing to `/arm_left_controller/follow_joint_trajectory/goal` topic while executing the play motion `move_joint` command.

**Comment by iqedgarmg** [comment]
Hi @saikishor thanks again for your response, adding the full vector of joint_names did the trick and the node is working now!. 

As an additional information, I also have to call the waitForServer() method on the MoveJointGroup constructor in order to achieve the communication: 

```
  MoveJointGroup::MoveJointGroup(const std::string& controller_name, const JointNames& joint_names)
    : busy_(false),
      controller_name_(controller_name),
      joint_names_(joint_names),
      client_(controller_name_ + "/follow_joint_trajectory", false)
  { 
    //Wait for server
    client_.waitForServer(ros::Duration(0.5));
  }
```

I wrote in this comment my node with the suggestions if it is useful for someone with the same problem: 

```
//Import basic libraries
#include <ros/ros.h>
#include <stdio.h>
#include <iostream>

//Play_motion libraries
#include "play_motion/move_joint_group.h"
#include <play_motion_msgs/PlayMotionResult.h>

//ROS messages
#include <trajectory_msgs/JointTrajectoryPoint.h>
#include <ros/duration.h>

//Metodo principal
int main(int argc, char** argv)
{
    //Init rosnode
    ros::init(argc, argv, "talker_cpp");
    ros::NodeHandle n("~");

    //Init controller information
    const std::string cont_name = "left_arm_controller";

    //Get joint names
    const std::vector<std::string> joint_names = std::vector<std::string>{std::string{"arm_left_1_joint"}, 
                                                                          std::string{"arm_left_2_joint"}, 
                                                                          std::string{"arm_left_3_joint"}, 
                                                                          std::string{"arm_left_4_joint"}, 
                                                                          std::string{"arm_left_5_joint"}, 
                                                                          std::string{"arm_left_6_joint"}, 
                                                                          std::string{"arm_left_7_joint"}};

    //Init control service
    play_motion::MoveJointGroup* control_service = new play_motion::MoveJointGroup(cont_name, joint_names);

    //Build example trajectory
    std::vector<trajectory_msgs::JointTrajectoryPoint> traj;
    trajectory_msgs::JointTrajectoryPoint msg; 
    msg.positions = {3.14, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
    msg.time_from_start = ros::Duration(0.5);
    traj.push_back(msg);

    //Send goal
    control_service->sendGoal(traj);
}
```

Thanks again! 

Greetings!

**Comment by saikishor** [comment]
@iqedgarmg Thanks for taking time and making a note on the `waitForServer()` issue.

**Comment by iqedgarmg** [comment]
Hi @saikishor, did you know if it is possible to send efforts for every joint directly?. I searched in the documentation as well as the robot manual but I cannot find information, as the joint_trajectory_controllers node just allows to set joint positions.

Is there a node or topic where I can define forces for every joint?

Thanks again for your help. 

Greetings!
